---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: redis-pod-autoscaler
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-pod-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: redis-pod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-pod-autoscaler
subjects:
  - kind: ServiceAccount
    name: redis-pod-autoscaler
    namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-pod-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-pod-autoscaler
    spec:
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      serviceAccountName: redis-pod-autoscaler
      containers:
        - name: redis-pod-autoscaler
          image: onfido/k8s-redis-pod-autoscaler
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          env:
            - name: INTERVAL
              value: "10"
            - name: REDIS_HOST
              value: "127.0.0.1"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_QUEUE_NAME
              value: "rsmq"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-pod-autoscaler
                  key: redis-pass
            - name: AUTOSCALING
              value: >
                1|10|1|default|deployment-name|queue-name;
                3|5|3|default|deployment-2-name|queue-2-name
            - name: LOGS
              value: HIGH
            - name: SLACK_HOOK
              value: SLACK_HOOK
